### ISSUE TITLE
Not bug

### ISSUE THREAD

**Issue by RohitVerma882** [termux/libandroid-support#10]
What is the use of this lib in termux and how to link it with bash statically?

**Comment by sylirre** [comment]
It provides C functions for working with wide characters. These functions normally available in libc, but on Android they either unavailable for OS version <= 7.0 or work in unexpected way.

For static linking just use a static variant of this library. In Termux it is available as part of package `libandroid-support-static`.

If you need it outside of Termux, see the following build steps: https://github.com/termux/termux-packages/blob/875752abeacaaddd645969169893e1d331355a46/packages/libandroid-support/build.sh#L21-L33
