### ISSUE TITLE
Many headers missing

### ISSUE THREAD

**Issue by rdb** [termux/libandroid-support#3]
It seems that many headers that are required to compile for older API versions in termux are missing.  Dropping http://rdb.name/android-support-headers.zip (taken from R17b) into the libandroid-support include directory seems to fix these issues, enabling me to compile my C++ program targeting API 14.

Should I file a PR to add these headers in, or are there good reasons why these headers are being excluded?

**Comment by ghost** [comment]
> there good reasons why these headers are being excluded?

Yes, these headers are provided by Android NDK. Libandroid-support implements only missing things.
For on-device clang, [ndk-sysroot](https://github.com/termux/termux-packages/blob/master/packages/ndk-sysroot/build.sh) package is provided which implements headers like stdio.h or other - same as in your archive. Also our NDK is higher version than R17b.
