### ISSUE TITLE
Internal Error. Could not early remove libandroid-support-aarch64 (2)

### ISSUE THREAD

**Issue by Karteesi** [termux/libandroid-support#6]
I wanted to install **python**, but this failed because library "libcrypto.so.1.1" was not found . So then I tried running **apt update** and then **apt upgrade**, but this failed with the error in the title above.

There was an explanation

> This installation run will require temporarily removing the essential package libandroid-support-aarch 64 due to a Conflicts/Pre-Depends loop. This is often bad, but if you really want to do it, activate the APT:Force-LoopBreak option.
>

Unfortunately, I have no idea what is going on here.  Can anyone help? I would really like to run **python**.

**Comment by Grimler91** [comment]
Looks like you haven't updated your packages in a quite long time. 

Easiest fix is to run `rm -rf $PREFIX` and then restart termux. This will remove all installed packages and give you a fresh installation. $HOME is left intact though

See also https://github.com/termux/termux-packages/issues/4129
